COMPILER=g++

BOOST_DIR=boost_1_53_0
GALIB_DIR=galib247

SIMULATION1=t1
EVOLUTIONARY_SIMULATION_BY_ENVIRONMENT=EvolutionaryCompetitionByEnvironment
SIMULATION_BY_ENVIRONMENT_AND_N=EvolutionaryCompetitionByEnvironmentAndLearningLength
SIMULATION4=t4
ENVIRONMENT=environment
BETAENVIRONMENT=betaenvironment
UTIL=util
COMMON=common


all: $(SIMULATION1) $(EVOLUTIONARY_SIMULATION_BY_ENVIRONMENT) $(SIMULATION_BY_ENVIRONMENT_AND_N) $(SIMULATION4)

$(SIMULATION1): $(SIMULATION1).o $(UTIL).o $(BETAENVIRONMENT).o
	$(CXX) $@.o $(UTIL).o $(BETAENVIRONMENT).o -o $@ -L$(GALIB_DIR)/ga -lga -lm

$(SIMULATION1).o: $(SIMULATION1).cpp $(UTIL).h $(COMMON).h $(BETAENVIRONMENT).h
	$(CXX) -c $(SIMULATION1).cpp -o $@ -I$(BOOST_DIR) -I$(GALIB_DIR)
	
$(EVOLUTIONARY_SIMULATION_BY_ENVIRONMENT): $(EVOLUTIONARY_SIMULATION_BY_ENVIRONMENT).o $(UTIL).o $(BETAENVIRONMENT).o
	$(CXX) $@.o $(UTIL).o $(BETAENVIRONMENT).o -o $@ -L$(GALIB_DIR)/ga -lga -lm

$(EVOLUTIONARY_SIMULATION_BY_ENVIRONMENT).o: $(EVOLUTIONARY_SIMULATION_BY_ENVIRONMENT).cpp $(UTIL).h $(COMMON).h $(BETAENVIRONMENT).h
	$(CXX) -c $(EVOLUTIONARY_SIMULATION_BY_ENVIRONMENT).cpp -o $@ -I$(BOOST_DIR) -I$(GALIB_DIR)
	
$(SIMULATION_BY_ENVIRONMENT_AND_N): $(SIMULATION_BY_ENVIRONMENT_AND_N).o $(UTIL).o $(BETAENVIRONMENT).o
	$(CXX) $@.o $(UTIL).o $(BETAENVIRONMENT).o -o $@ -L$(GALIB_DIR)/ga -lga -lm

$(SIMULATION_BY_ENVIRONMENT_AND_N).o: $(SIMULATION_BY_ENVIRONMENT_AND_N).cpp $(UTIL).h $(COMMON).h $(BETAENVIRONMENT).h
	$(CXX) -c $(SIMULATION_BY_ENVIRONMENT_AND_N).cpp -o $@ -I$(BOOST_DIR) -I$(GALIB_DIR)

$(SIMULATION4): $(SIMULATION4).o $(UTIL).o $(BETAENVIRONMENT).o
	$(CXX) $@.o $(UTIL).o $(BETAENVIRONMENT).o -o $@ -L$(GALIB_DIR)/ga -lga -lm

$(SIMULATION4).o: $(SIMULATION4).cpp $(UTIL).h $(COMMON).h $(BETAENVIRONMENT).h
	$(CXX) -c $(SIMULATION4).cpp -o $@ -I$(BOOST_DIR) -I$(GALIB_DIR)

$(ENVIRONMENT).o: $(ENVIRONMENT).cpp $(ENVIRONMENT).h
	$(COMPILER) -c $(ENVIRONMENT).cpp -o $@ -I$(BOOST_DIR) -I$(GALIB_DIR)

$(BETAENVIRONMENT).o: $(BETAENVIRONMENT).cpp $(BETAENVIRONMENT).h $(ENVIRONMENT).h $(UTIL).h
	$(COMPILER) -c $(BETAENVIRONMENT).cpp -o $@ -I$(BOOST_DIR) -I$(GALIB_DIR)

$(UTIL).o: $(UTIL).cpp $(UTIL).h
	$(COMPILER) -c $(UTIL).cpp -o $@ -I$(BOOST_DIR) -I$(GALIB_DIR)

clean:
	$(RM) $(SIMULATION1) $(EVOLUTIONARY_SIMULATION_BY_ENVIRONMENT) $(SIMULATION_BY_ENVIRONMENT_AND_N) $(SIMULATION4) *.o *.dat *~
